namespace GeometricAlgebraFulcrumLib.Lite.Graphics.Rendering.BabylonJs.Constants
{
    public enum GrBabylonJsAlphaBlendingMode
    {
        Add,
        AlphaToColor,
        Combine,
        Disable,
        EquationAdd,
        EquationDarken,
        EquationMax,
        EquationMin,
        EquationReverseSubtract,
        EquationSubtract,
        Exclusion,
        Interpolate,
        LayerAccumulate,
        Maximized,
        Multiply,
        OneOne,
        OneOneOneOne,
        OneOneOneZero,
        PreMultiplied,
        PreMultipliedPorterDuff,
        ReverseOneMinus,
        ScreenMode,
        SrcDstOneMinusSrcAlpha,
        Subtract
    }
}